### PR TITLE
Added Modern Navigation Options in SharePoint Online

### PR DESCRIPTION
**Pull request by skaggej**
Use this presentation as a guided tour to help decision makers select an effective navigation strategy in the modern SharePoint Online experience.

### CODE REVIEW

**Comment by sympmarc** [comment]
We’re generally going for textual content in this repo, but that doesn’t mean we can’t use this. As soon as I can, I’ll take a look through it and figure out how we can use it. Thanks for the submission!

**Comment by skaggej** [comment]
Completely makes sense...reviewed the team site vs. comm site page and we can definitely turn this PPT into something similar on navigation options. Probably good to not merge this PR and I'll get something better started. :-)

**Comment by sympmarc** [comment]
Great! You’re still submission number 2!

**Comment by skaggej** [comment]
Ok...added a new MD page with guidance text.  :-)

**Pull request merged**
