### PR TITLE
Designing solution for scale

### PR DESCRIPTION
**Pull request by pkbullock**
Hope its ok first a first article submission. If you need any changes let me know. 

Reference #16

### CODE REVIEW

**Comment by sympmarc** [comment]
Thanks, Paul! I've merged the PR and will take a look...

**Comment by sympmarc** [comment]
Ah, the debate about whether to change British spellings to American spellings; I did not. :)

I did fix some small formatting stuff; you had a weird character peppered throughout: "￼". It wasn't hard to find them all!

**Comment by pkbullock** [comment]
Thx @sympmarc, if you decide to change it, feel free to ping me and ill adjust for my future submissions. I don't mind really.

**Comment by sympmarc** [comment]
I don't want to be that American.

**Pull request merged**
